cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove,
        name='cart_remove'),
]

ozfriend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "OZFriend Management System"
admin.site.site_title = "OZFriendAdmin"


urlpatterns = [
    # Fake Model for Reports(first line)
    url(r'^admin/reports/', include('reports.urls', namespace='reports')),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

reports/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.report_list, name='report_list'),
    url(r'^annual$', views.annual_report, name='annual_report'),
    url(r'^monthly$', views.monthly_report, name='monthly_report'),
    url(r'^payer$', views.payer_report, name='payer_report'),
    url(r'^capital$', views.capital_report, name='capital_report'),
]

reports/models.py
from django.db import models

# Create your models here.

reports/forms.py
import datetime
from django import forms
from pytz import timezone
from django.contrib.admin import widgets

tz = timezone('Australia/Sydney')


class ReportDateForm(forms.Form):
    date_from = forms.DateField(widget=widgets.AdminDateWidget(),
                                label="From", input_formats=['%Y-%m-%d'])
    date_to = forms.DateField(widget=widgets.AdminDateWidget(), label="To")


class ReportPayerForm(ReportDateForm):
    over = forms.IntegerField(initial=60,
                              label="* Quantity of Items with Price Over")

reports/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from .reports import Report, YMD
from .forms import ReportDateForm, ReportPayerForm
# use @never_cache # useless here
from django.views.decorators.cache import never_cache
import datetime


CONTEXT = {'site_header': 'OZFriend Management System',
           'site_title': 'OZFriend', }


@staff_member_required
def report_list(req):
    context = {}
    context['site_header'] = CONTEXT['site_header']
    context['site_title'] = CONTEXT['site_title']
    context['marry_count'] = "我们结婚{0}年{1}个月零{2}天啦~~~~ \
        一共度过了{3}天快乐的时光！".format(*YMD())
    context['app_list'] = [{'name': 'Report'}]
    context['title'] = 'Reports administration'
    return render(req, "reports/report_index.html", context)


@staff_member_required
@never_cache
def annual_report(req):
    context = {}
    context['site_header'] = CONTEXT['site_header']
    context['site_title'] = CONTEXT['site_title']
    context['report_type'] = 'Annual'
    context['title'] = 'Annual Report'
    context['report_url'] = 'annual_report'
    context['has_permission'] = True
    context['site_url'] = reverse('shop:product_list')
    if req.method == 'POST':
        form = ReportDateForm(req.POST)
        if form.is_valid():
            cd = form.cleaned_data
            date_from = cd["date_from"]
            date_to = cd["date_to"]
            context['report'] = Report().get_this_year(date_from, date_to)
            context['report_date_form'] = form
            return render(req, "reports/report_detail.html", context)
        else:
            context['report'] = Report().get_this_year()
            context['report_date_form'] = form
            context['report_date_form'].fields['date_to'].initial = \
                datetime.datetime.now().date()
            context['report_date_form'].fields['date_from'].initial = \
                datetime.datetime.now().date() - datetime.timedelta(30)
            return render(req, "reports/report_detail.html", context)
    else:
        context['report'] = Report().get_this_year()
        context['report_date_form'] = ReportDateForm()
        context['report_date_form'].fields['date_to'].initial = \
            datetime.datetime.now().date()
        context['report_date_form'].fields['date_from'].initial = \
            datetime.datetime.now().date() - datetime.timedelta(30)
        return render(req, "reports/report_detail.html", context)


@staff_member_required
def monthly_report(req):
    context = {}
    context['site_header'] = CONTEXT['site_header']
    context['site_title'] = CONTEXT['site_title']
    context['has_permission'] = True
    context['site_url'] = reverse('shop:product_list')
    context['report_type'] = 'Monthly'
    context['report_url'] = 'monthly_report'
    context['title'] = 'Monthly Report'
    if req.method == 'POST':
        form = ReportDateForm(req.POST)
        if form.is_valid():
            cd = form.cleaned_data
            date_from = cd["date_from"]
            date_to = cd["date_to"]
            context['report'] = Report().get_this_month(date_from, date_to)
            context['report_date_form'] = form
            return render(req, "reports/report_detail.html", context)
        else:
            context['report'] = Report().get_this_month()
            context['report_date_form'] = form
            context['report_date_form'].fields['date_to'].initial = \
                datetime.datetime.now().date()
            context['report_date_form'].fields['date_from'].initial = \
                datetime.datetime.now().date() - datetime.timedelta(30)
            return render(req, "reports/report_detail.html", context)
    else:
        context['report'] = Report().get_this_month()
        context['report_date_form'] = ReportDateForm()
        context['report_date_form'].fields['date_to'].initial = \
            datetime.datetime.now().date()
        context['report_date_form'].fields['date_from'].initial = \
            datetime.datetime.now().date() - datetime.timedelta(30)
        return render(req, "reports/report_detail.html", context)


@staff_member_required
def payer_report(req):
    context = {}
    context['site_header'] = CONTEXT['site_header']
    context['site_title'] = CONTEXT['site_title']
    context['has_permission'] = True
    context['site_url'] = reverse('shop:product_list')
    context['report_type'] = 'Payer'
    context['report_url'] = 'payer_report'
    context['title'] = 'Payer Report'
    if req.method == 'POST':
        form = ReportPayerForm(req.POST)
        if form.is_valid():
            cd = form.cleaned_data
            datetime_from = cd["date_from"]
            datetime_to = cd["date_to"]
            over = cd["over"]
            context['report'] = Report().get_payers_year(datetime_from,
                                                         datetime_to, over)
            context['report_date_form'] = form
            return render(req, "reports/report_detail.html", context)
        else:
            context['report'] = Report().get_payers_year()
            context['report_date_form'] = form
            context['report_date_form'].fields['date_to'].initial = \
                datetime.datetime.now().date()
            context['report_date_form'].fields['date_from'].initial = \
                datetime.datetime.now().date() - datetime.timedelta(30)
            return render(req, "reports/report_detail.html", context)
    else:
        context['report'] = Report().get_payers_year()
        context['report_date_form'] = ReportPayerForm()
        context['report_date_form'].fields['date_to'].initial = \
            datetime.datetime.now().date()
        context['report_date_form'].fields['date_from'].initial = \
            datetime.datetime.now().date() - datetime.timedelta(30)
        return render(req, "reports/report_detail.html", context)


@staff_member_required
def capital_report(req):
    context = {}
    context['site_header'] = CONTEXT['site_header']
    context['site_title'] = CONTEXT['site_title']
    context['has_permission'] = True
    context['site_url'] = reverse('shop:product_list')
    context['report_url'] = 'capital_report'
    context['title'] = 'Capital Report'
    if req.method == 'POST':
        form = ReportDateForm(req.POST)
        if form.is_valid():
            cd = form.cleaned_data
            datetime_from = cd["date_from"]
            datetime_to = cd["date_to"]
            context['report'] = Report().get_capital_year(datetime_from,
                                                          datetime_to)
            context['report_date_form'] = form
            return render(req, "reports/report_detail.html", context)
        else:
            context['report_date_form'] = form
            context['report'] = Report().get_capital_year()
            context['report_date_form'].fields['date_to'].initial = \
                datetime.datetime.now().date()
            context['report_date_form'].fields['date_from'].initial = \
                datetime.datetime.now().date() - datetime.timedelta(30)
            return render(req, "reports/report_detail.html", context)
    else:
        context['report'] = Report().get_capital_year()
        context['report_date_form'] = ReportDateForm()
        context['report_date_form'].fields['date_to'].initial = \
            datetime.datetime.now().date()
        context['report_date_form'].fields['date_from'].initial = \
            datetime.datetime.now().date() - datetime.timedelta(30)
        return render(req, "reports/report_detail.html", context)

reports/templates/reports/ozfriend_report_list.html
<div class="app-reports module">
    <table>
        <caption>
            <a href="/admin/reports/" class="section">Statistic Reports</a>
        </caption>
        <tr class="model-reports">
            <th scope="row"><a href="/admin/reports/annual">Annual Report</a></th>
            <td><a href="" class="addlink">Add</a></td>
            <td><a href="" class="changelink">Change</td>
        </tr>
        <tr class="model-reports">
            <th colspan=1 scope="row"><a href="/admin/reports/monthly">Monthly Report</a></th>
            <td><a href="" class="addlink">Add</a></td>
            <td><a href="" class="changelink">Change</td>
        </tr>
        <tr class="model-reports">
            <th colspan=1 scope="row"><a href="/admin/reports/payer">Payer Report</a></th>
            <td><a href="" class="addlink">Add</a></td>
            <td><a href="" class="changelink">Change</td>
        </tr>
        <tr class="model-reports">
            <th colspan=1 scope="row"><a href="/admin/reports/capital">Capital Report</a></th>
            <td><a href="" class="addlink">Add</a></td>
            <td><a href="" class="changelink">Change</td>
        </tr>
    </table>
</div>

reports/templates/reports/report_detail.html
{% extends "admin/app_index.html" %}

{% load static %}
{% load ozfriend_tags %}

{% block extrahead %}{{ block.super }}
<script src="{% static 'admin/js/core.js' %}"></script>
<script src="/admin/jsi18n/"></script>
<script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<script src="{% static 'admin/js/jquery.init.js' %}"></script>
<script src="{% static 'admin/js/calendar.js' %}"></script>
<script src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>

<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static 'admin/' %}{% endfilter %}";</script>
<script src="{% static 'admin/js/prepopulate.js' %}"></script>
<script src="{% static 'admin/js/prepopulate_init.js' %}"></script>

{% endblock %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'reports/css/reports.css' %}" />
{% endblock %}



{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">Home</a>
&rsaquo; <a href="{% url 'reports:report_list' %}">Report</a>
&rsaquo; {{ report_type }}
</div>
{% endblock %}
{% block content %}
<div id="content-main">
{% if title in 'Annual Report' or title in 'Monthly Report' %}
<div class="oz-reports">
    <table>
        <caption>销量统计</caption>
        <tr>
            <th scope="row">订单数量:</th>
            <td>{{ report.order_num }}</td>
            <td>张</td>
        </tr>
        <tr>
            <th colspan=1 scope="row">产品销量:</th>
            <td>{{ report.item_num }}</td>
            <td>件</td>
        </tr>
    </table>
</div>
<div class="oz-reports">
    <table>
        <caption>财政统计</caption>
        <tr>
            <th scope="row">营业额(RMB|AUD):</th>
            <td>{{ report.price_rmb|show_rmb }}</td>
            <td>{{ report.price_aud|show_aud }}</td>
        </tr>
        <tr>
            <th colspan=1 scope="row">成本(RMB|AUD):</th>
            <td>{{ report.expense_rmb|show_rmb }}</td>
            <td>{{ report.expense_aud_cn|show_aud }}(中国)+{{ report.expense_aud_oz|show_aud }}(澳洲)</td>
        </tr>
    </table>
</div>

<div class="oz-reports">
    <table>
        <caption>利润统计</caption>
        <tr>
            <th scope="row">使用汇率:</th>
            <td>1AUD={{ report.fx.fx|floatformat:2 }}RMB</td>
        </tr>
        <tr>
            <th colspan=1 scope="row">净收入(AUD):</th>
            <td colspan=2>{{ report.net_income_aud|show_aud }}</td>
        </tr>
    </table>
</div>
<div class="oz-reports">
    <table>
        <caption>其他</caption>
        <tr>
            <th scope="row">校验状态:</th>
            <td>{% if report.parity %}<span class="green-all">校验成功</span>{% else %}<span class="warning-all">校验失败</span>{% endif %}</td>
        </tr>
        {% if report.error %}
        <tr class="warning-all">
            <th>错误订单:</th>
            <td>{% for e in report.error %}{% if forloop.last %}{{ e }}{% else %}{{ e }}, {% endif %}{% endfor %}</td>
        </tr>
        {% endif %}
        {% if report.lost %}
        <tr class="warning-all">
            <th>赔本订单:</th>
            <td>{% for l in report.lost %}{% if forloop.last %}{{ l }}{% else %}{{ l }}, {% endif %}{% endfor %}</td>
        </tr>
        {% endif %}
        {% if report.warn %}
        <tr class="warning-all">
            <th>警告订单:产品:</th>
            <td>{% for w in report.warn %}{% if forloop.last %}{{ w }}{% else %}{{ w }}, {% endif %}{% endfor %}</td>
        </tr>
        {% endif %}
    </table>
</div>
{% endif %}
{% if title in 'Payer Report' %}
<div class="oz-reports">
    <table class="payer">
        <caption>按照下单人统计</caption>
        <tr>
            <th>下单人</th>
            <th>订单数</th>
            <th>*货品数</th>
            <th>售价AUD</th>
            <th>成本AUD</th>
            <th>利润AUD</th>
        </tr>
        {% for i in report.payer_list %}
        <tr>
            <td>{{ i.0 }}</td>
            <td>{{ i.1.order_num }}单</td>
            <td>{{ i.1.item_num }}件</td>
            <td>{{ i.1.price|show_aud }}</td>
            <td>{{ i.1.expense|show_aud }}</td>
            <td>{{ i.1.profit|show_aud }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}
{% if title in 'Capital Report' %}
<div class="oz-reports">
    <table class="payer">
        <caption>Capital Report</caption>
        <tr>
            <th></th>
            <th>澳洲AUD</th>
            <th>中国AUD</th>
            <th>中国RMB</th>
        </tr>
        <tr>
            <th scope="row">总支出:</th>
            <td>{{ report.expense_aud_oz|show_aud }}</td>
            <td>{{ report.expense_aud_cn|show_aud }}</td>
            <td>{{ report.expense_rmb|show_rmb }}</td>
        </tr>
        <tr>
            <th scope="row">总入账:</th>
            <td>{{ report.price_aud|show_aud }}</td>
            <td>-</td>
            <td>{{ report.price_rmb|show_rmb }}</td>
        </tr>
        <tr>
            <th colspan=2 scope="row">总换汇: ({{ report.fx.num }}笔, 1$={{ report.fx.fx|show_rmb }})</th>
            <td>{{ report.fx.aud_cn|show_aud }}</td>
            <td>{{ report.fx.rmb|show_rmb }}</td>
        </tr>
        <tr>
            <th scope="row">总结:</th>
            <td>{{ report.summary.expense_aud_oz|show_aud }}</td>
            <td>{{ report.summary.expense_aud_cn|show_aud }}</td>
            <td>{{ report.summary.price_rmb_cn|show_rmb }} (={{ report.summary.price_rmb_cn|rmb2aud:report.fx.fx|show_aud }})</td>
        </tr>
    </table>
</div>
{% endif %}
</div>
{% endblock %}
{% block sidebar %}
<div id="content-related">
    <div id="report_date">
        <table>
            <caption><h2>日期范围<h2></caption>
            <tr><th>From:</th><th>{{ report.begin }}</th></tr>
            <tr><th>To:</th><th>{{ report.end }}</th></tr>
        </table>
    </div>
    <div id="report_date_form">
    {% if title in 'Annual Report' %}
    <form action="{% url "reports:annual_report" %}" method="post" width="10px">
        {{ report_date_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Search"></p>
    </form>
    {% endif %}
    {% if title in 'Monthly Report' %}
    <form action="{% url "reports:monthly_report" %}" method="post" width="10px">
        {{ report_date_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Search"></p>
    </form>
    {% endif %}
    {% if title in 'Payer Report' %}
    <form action="{% url "reports:payer_report" %}" method="post" width="10px">
        {{ report_date_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Search"><p>
    </form>
    {% endif %}
    {% if title in 'Capital Report' %}
    <form action="{% url "reports:capital_report" %}" method="post" width="10px">
        {{ report_date_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Search"><p>
    </form>
    {% endif %}
</div>
{% endblock %}

reports/templates/reports/report_index.html
{% extends "admin/app_index.html" %}
{% block content %}
    {% include "reports/ozfriend_report_list.html" %}
    {% block ozfriendreport %}{{ block.super }}{% endblock %}
{% endblock %}
{% block sidebar %}
{% if marry_count %}<h1 color="#417690;">{{ marry_count }}</h1>{% endif %}
{% endblock %}