account/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^validate/$', views.account_validate_img,
        name='account_validate_img'),
    url(r'^orderitem/$', views.ajax_orderitem, name='ajax_orderitem'),
    url(r'^$', views.dashboard, name='dashboard'),
]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove,
        name='cart_remove'),
]

ozfriend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "OZFriend Management System"
admin.site.site_title = "OZFriendAdmin"


urlpatterns = [
    # Fake Model for Reports(first line)
    url(r'^admin/reports/', include('reports.urls', namespace='reports')),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^shop/inner/$', views.product_inner, name='product_inner'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):
    chinese = models.CharField(max_length=200, db_index=True, unique=True)
    name = models.CharField(max_length=200, db_index=True, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('id',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    chinese = models.CharField(max_length=200, db_index=True, unique=True)
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=200, db_index=True, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    reference = models.URLField(max_length=300, blank=True)
    description = models.TextField(blank=True)
    price_rmb = models.DecimalField(max_digits=6, decimal_places=2, default=0,
                                    verbose_name="Selling Price RMB")
    price_aud = models.DecimalField(max_digits=6, decimal_places=2, default=0,
                                    verbose_name="Selling Price AUD")
    expense_aud = models.DecimalField(max_digits=6, decimal_places=2,
                                      default=0,
                                      verbose_name="Buying Cost AUD")
    expense_rmb = models.DecimalField(max_digits=6, decimal_places=2,
                                      default=0,
                                      verbose_name="Buying Cost RMB")
    weight = models.PositiveIntegerField(blank=True, default=0,
                                         verbose_name="Weight (g)")
    stock = models.PositiveIntegerField(default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def image_path(instance, filename):
        if instance.slug:
            brand = instance.slug.split('-')[0]
        else:
            brand = "default"
        filename = "IMAGE_"+instance.slug+"."+filename.split('.')[-1]
        return '{0}/{1}'.format(brand, filename)

    def ico_path(instance, filename):
        if instance.slug:
            brand = instance.slug.split('-')[0]
        else:
            brand = "default"
        filename = "ICO_"+instance.slug+"."+filename.split('.')[-1]
        return '{0}/{1}'.format(brand, filename)

    ico = models.ImageField(upload_to=ico_path)
    image = models.ImageField(upload_to=image_path, blank=True)

    class Meta:
        ordering = ('chinese',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.chinese

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 9)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False,
                                widget=forms.HiddenInput)

shop/forms.py
from django import forms


class QuickSearch(forms.Form):
    chinese = forms.CharField(max_length=50, widget=forms.TextInput(
            attrs={'class': 'search_ME', 'id': 'search-text'}))

shop/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.http import HttpResponse
import json
from .forms import QuickSearch


@staff_member_required
def product_inner(req, search_text=""):
    if req.is_ajax():
        if req.method == 'GET':
            q = req.GET['q']
            if q:
                recs = Product.objects.filter(chinese__contains=q)[:10]
                rejson = []
                for rec in recs:
                    rejson.append(rec.chinese)
                return HttpResponse(json.dumps(rejson),
                                    content_type='application/json')
            else:
                return HttpResponse(json.dumps([]),
                                    content_type='application/json')
        elif req.method == 'POST':
            search_text = req.POST['search_text']
            product = get_object_or_404(Product, chinese=search_text)
            resp = {'id': product.id, 'expense_aud': str(product.expense_aud),
                    'expense_rmb': str(product.expense_rmb),
                    'price_rmb': str(product.price_rmb),
                    'price_aud': str(product.price_aud)}
            return HttpResponse(json.dumps(resp),
                                content_type='application/json')


def product_list(req, category_slug=None, search_text=""):
    if req.is_ajax():
        q = req.GET['q']
        if q:
            recs = Product.objects.filter(chinese__contains=q)[:10]
            rejson = []
            for rec in recs:
                rejson.append(rec.chinese)
            return HttpResponse(json.dumps(rejson),
                                content_type='application/json')
        else:
            return HttpResponse(json.dumps([]),
                                content_type='application/json')

    if req.method == 'POST':
        form = QuickSearch(req.POST)
        if form.is_valid():
            cd = form.cleaned_data
            search_text = cd["chinese"]

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True,
                                      chinese__contains=search_text)

    cart_product_form = CartAddProductForm()
    quick_search_form = QuickSearch()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    LIMIT = 32  # Number of items showing on each page!
    page = req.GET.get('page')   # Get the page number!
    paginator = Paginator(products, LIMIT)
    try:
        pageprods = paginator.page(page)
    except PageNotAnInteger:
        pageprods = paginator.page(1)
    except EmptyPage:
        pageprods = paginator.page(paginator.num_pages)

    return render(req, 'shop/list.html', {
            'category': category, 'categories': categories,
            'pageprods': pageprods, 'cart_product_form': cart_product_form,
            'quick_search_form': quick_search_form})


def product_detail(req, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    categories = product.category.all()
    cart_product_form = CartAddProductForm()
    return render(req, 'shop/detail.html', {
            'product': product,
            'categories': categories,
            'cart_product_form': cart_product_form})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}OZ Friend{% endblock %}</title>
  <link href="{% static "shop/css/base.css" %}" rel="stylesheet">
  <link href="{% static "shop/css/ozfriend.css" %}" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static "shop/img/favicon.ico" %}"/>
  {% block extracss %}
  {% endblock %}

</head>
  <div id="header">
    <a href="/" class="logo">Welcome to OZ Friend's Store!</a>
    <span class="user">
    {% if request.user.is_authenticated %}
      Hello <a href="{% url "account:dashboard" %}">{{request.user.first_name}}</a>,
        <a href="{% url "account:logout" %}">Log out</a>
    {% else %}
      <a href="{% url "account:login" %}">Log in</a>
    {% endif %}
    </span>
  </div>
  <div id="subheader">
    <div class="cart">
      {% with total_items=cart|length %}
        <span {% if total_items %}{% else %}class="hide"{% endif %}>
          <p class=no-break> Your Cart:</p> 
          <a href="{% url "cart:cart_detail" %}">
            <p class=no-break id=js-item-number>{{ total_items }}</p> item{{ total_items|pluralize }},
            ￥<p class=no-break id=js-price-total>{{ cart.get_total_price_rmb|floatformat:2 }}</p></a>
        </span>
      {% endwith %}
    </div>
  </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="javascript">
    {% block javascript %}
    {% endblock %}
  </div>

</html>

shop/templates/shop/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.title }}{% else %}Product{% endif %}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% elif  product.ico %}
              {{ product.ico.url }}{% else %}{% static "img/no_img.png" %}{% endif %}">
    <h1>{{ product.chinese }}</h1>
    <h2>{{ product.name }}</h2>
      <h2>所属分类：
        {% for c in categories %}
          <a href="{{ c.get_absolute_url }}">{{ c.chinese }} </a>
        {% endfor %}
      </h2>
    <p class="price">RMB: {{ product.price_rmb }} </p>
      <form action="{% url "cart:cart_add" product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
      </form>
      {{ product.description|linebreaks }}
  </div>
{% endblock %}

shop/templates/shop/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.chinese }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list" %}">All</a>
      </li>
      <li>
        {% for c in categories %}
          <li {% if category.slug == c.slug %}class="selected"{% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.chinese }}</a>
          </li>
        {% endfor %}
      </li>
      <div id="live-search">
        <form action="{% url "shop:product_list" %}" method="post" width="10px">
          {{ quick_search_form.as_p }}
          {% csrf_token %}
          <input type="submit" value="Search">
        </form>
        <div id="search-result">
        </div>
      </div>
    </ul>
  </div>

  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.chinese }}{% else %}Products{% endif %}</h1>
    {% for p in pageprods.object_list %}
      <div class="item">
        <a href="{{ p.get_absolute_url }}">
          <img src="{% if p.ico %}{{ p.ico.url }}{% else %}{% static "shop/img/no_image.png" %}{% endif %}"
        </a><br>
        <a class="chinese" href="{{ p.get_absolute_url }}">{{ p.chinese|slice:":" }}</a><br>
        ￥<p class=no-break id=js-item-price_rmb>{{ p.price_rmb }}</p><p class=no-break>, </p><p class=no-break> {{ p.weight }}</p>g
        <form class='quick' action="{% url "cart:cart_add" p.id %}" method="post">
            <input type="hidden" name="quantity" value=1 id="id_quantity">
            <input type="hidden" name="update" value="False" id="id_update">
            {% csrf_token %}
            <button class='js-ajax-submit'>+</button>
        </form>
      </div>
    {% endfor %}
  </div>
    <div id="pagination">
      <div>
        {% if pageprods.has_previous %}
        <a href="?page={{ pageprods.previous_page_number }}">Previous</a>
        {% endif %}
        {% if pageprods.paginator.num_pages > 1 %}
          {% for page_number in pageprods.paginator.page_range %}
            {% ifequal page_number pageprods.number %}
              {{ page_number }}
            {% else %}
              <a href="?page={{ page_number }}">{{ page_number }}</a>
            {% endifequal %}
          {% endfor %}
        {% endif %}
        {% if pageprods.has_next %}
        <a href="?page={{ pageprods.next_page_number }}">Next</a>
        {% endif %}
      </div>
    </div>
{% endblock %}
{% block javascript %}
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="{% static "shop/js/ozfriend.js" %}"></script>
{% endblock %}